# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180510_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchonyoutube',
            name='image_file',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
