# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180510_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchonyoutube',
            name='image_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
