# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180510_0444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchOnYoutube',
        ),
    ]
